/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _rootCapacitorRouteImport } from './routes/__root.capacitor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'

const _rootCapacitorRoute = _rootCapacitorRouteImport.update({
  id: '/__root/capacitor',
  path: '/capacitor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppRoute
  '/login': typeof LoginRoute
  '/capacitor': typeof _rootCapacitorRoute
}
export interface FileRoutesByTo {
  '/': typeof AppRoute
  '/login': typeof LoginRoute
  '/capacitor': typeof _rootCapacitorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRoute
  '/login': typeof LoginRoute
  '/__root/capacitor': typeof _rootCapacitorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/capacitor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/capacitor'
  id: '__root__' | '/_app' | '/login' | '/__root/capacitor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRoute
  LoginRoute: typeof LoginRoute
  _rootCapacitorRoute: typeof _rootCapacitorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__root/capacitor': {
      id: '/__root/capacitor'
      path: '/capacitor'
      fullPath: '/capacitor'
      preLoaderRoute: typeof _rootCapacitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRoute,
  LoginRoute: LoginRoute,
  _rootCapacitorRoute: _rootCapacitorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
